### ISSUE TITLE
Dry run or print plan?

### ISSUE THREAD

**Issue by jdub** [tableau/tableau-migration-sdk#7]
Is there any way to run it in dry run mode, or print out a plan once built? (I'm using the Python wrapper.)

**Comment by rbanderton** [comment]
Dry runs are a bit of an advanced topic, but we do have an API simulator that can be used to test migrations. The most basic way to do a dry run is to use a simulated destination site from a real source site. The way to do this in Python is to use the `create_api_simulator` parameter of the `to_destination_tableau_cloud` [plan builder method](https://tableau.github.io/migration-sdk/python_wrapper/tableau_migration.migration_engine.PyMigrationPlanBuilder.html#tableau_migration.migration_engine.PyMigrationPlanBuilder.to_destination_tableau_cloud). That will tell the migrator to use a simulated empty site for the destination instead of connecting to the real site. Please note that our API simulator is focused on helping validate that migration logic is correct, and isn't intended to fully simulate every detail of the APIs.

For plan printing - we don't have a standard serializer for plans as we're gathering feedback on preferred file formats, and serialization of hooks is currently non-trivial. You can of course develop your own serializer/print function based on the [plan object](https://tableau.github.io/migration-sdk/python_wrapper/tableau_migration.migration_engine.PyMigrationPlan.html) returned from the `build` method.

**Comment by jdub** [comment]
Thanks very much @rbanderton, that's enough to get me started!
